In [1]:
import pandas as pd

train_df = pd.read_csv("data/train.csv")
test_df = pd.read_csv("data/test.csv")

print("Train Data Shape: ", train_df.shape)
display(train_df.head(1))

print("Test Data Shape: ", test_df.shape)
display(test_df.head(1))

Train Data Shape:  (188533, 13)

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,0,MINI,Cooper S Base,2007,213000,Gasoline,172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel,A/T,Yellow,Gray,None reported,Yes,4200

Test Data Shape:  (125690, 12)

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title
0,188533,Land,Rover LR2 Base,2015,98000,Gasoline,240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,6-Speed A/T,White,Beige,None reported,Yes

In [2]:
X = train_df.copy()
X['binned_mileage'] = X['milage']//1000 # binning mileage 
cols = ['model','engine','binned_mileage'] # Take 3 key features
df = (
    X.groupby(cols)['price']
    .agg(['count','mean','std','min','max'])
    .dropna() # only keep rows with duplicate features
)
df[df['std']>75000].sort_values(by='std', ascending=False)

,,,count,mean,std,min,max
model,engine,binned_mileage,,,,,
QX60 Base,265.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,84,2,1.484841e+06,2.077822e+06,15599,2954083
Thunderbird Deluxe,280.0HP 3.9L 8 Cylinder Engine Gasoline Fuel,95,2,1.484841e+06,2.077822e+06,15599,2954083
DeVille Base,â€“,85,2,1.487042e+06,2.074710e+06,20000,2954083
Highlander XLE,2.4L I4 16V PDI DOHC Turbo,13,2,1.490979e+06,2.069142e+06,27875,2954083
Rover Range Rover 3.0L V6 Supercharged HSE,380.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,29,2,1.491542e+06,2.068346e+06,29000,2954083
...,...,...,...,...,...,...,...
AMG GLS 63 4MATIC,603.0HP 4.0L 8 Cylinder Engine Gasoline/Mild Electric Hybrid,49,3,9.560000e+04,7.530120e+04,35000,179900
Gladiator Rubicon,285.0HP 3.6L V6 Cylinder Engine Gasoline Fuel,14,6,7.624983e+04,7.529534e+04,30000,229000
Camaro 2SS,455.0HP 6.2L 8 Cylinder Engine Gasoline Fuel,20,14,6.399986e+04,7.527363e+04,4399,319900
MDX w/Technology Package,3.5 Liter SOHC,11,3,8.823200e+04,7.516859e+04,40798,174900
Corvette Z06,505.0HP 7.0L 8 Cylinder Engine Gasoline Fuel,1,4,7.005000e+04,7.513278e+04,6750,162500

In [11]:
# for test_df let us see the count for each group of model, engine and binned_mileage
test_df['binned_mileage'] = test_df['milage']//1000 # binning mileage 
cols = ['model', 'engine', 'binned_mileage'] # Take 3 key features
df = (
    test_df.groupby(cols)
    .size()
    .reset_index(name='count')
)
df = df.sort_values(by='count', ascending=False)
df = df[['model', 'engine', 'binned_mileage', 'count']]  # Reorder columns
df.head(10)

,model,engine,binned_mileage,count
22575,Corvette Stingray w/2LT,490.0HP 6.2L 8 Cylinder Engine Gasoline Fuel,2,74
55901,R1S Adventure Package,835.0HP Electric Motor Electric Fuel System,0,72
562,1500 Laramie,5.7L V8 16V MPFI OHV,16,56
22574,Corvette Stingray w/2LT,490.0HP 6.2L 8 Cylinder Engine Gasoline Fuel,1,48
44254,M4 Base,425.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,19,48
37837,Ghost Base,563.0HP 6.6L 12 Cylinder Engine Gasoline Fuel,79,47
44260,M4 Base,425.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,25,45
54175,Q5 S line Premium Plus,2.0 Liter TFSI,10,45
30913,F-150 XLT,375.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,67,45
22585,Corvette Stingray w/2LT,490.0HP 6.2L 8 Cylinder Engine Gasoline Fuel,12,45

In [17]:
# for each of the above rows in df, check in train_df if there are any with the same (model,engine,binned_mileage) then add train_mean_price, train_std_price, train_min_price, train_max_price, and train_count to the df
from tqdm import tqdm

temp_train_df = train_df.copy()
temp_train_df['binned_mileage'] = temp_train_df['milage'] // 1000  # binning mileage

for index, row in tqdm(df.head(100).iterrows(), total=100, desc="Processing first 100 rows"):
    model = row['model']
    engine = row['engine']
    binned_mileage = row['binned_mileage']
    train_df_filtered = temp_train_df[(temp_train_df['model'] == model) & (temp_train_df['engine'] == engine) & (temp_train_df['binned_mileage'] == binned_mileage)]
    if not train_df_filtered.empty:
        df.loc[index, 'train_mean_price'] = train_df_filtered['price'].mean()
        df.loc[index, 'train_std_price'] = train_df_filtered['price'].std()
        df.loc[index, 'train_min_price'] = train_df_filtered['price'].min()
        df.loc[index, 'train_max_price'] = train_df_filtered['price'].max()
        df.loc[index, 'train_count'] = len(train_df_filtered)
df.head(10)

Processing first 100 rows: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 100/100 [00:01<00:00, 90.80it/s]

,model,engine,binned_mileage,count,train_mean_price,train_std_price,train_min_price,train_max_price,train_count
22575,Corvette Stingray w/2LT,490.0HP 6.2L 8 Cylinder Engine Gasoline Fuel,2,74,73685.126050,26969.085423,29500.0,164725.0,119.0
55901,R1S Adventure Package,835.0HP Electric Motor Electric Fuel System,0,72,85687.265487,51477.360649,14000.0,449991.0,113.0
562,1500 Laramie,5.7L V8 16V MPFI OHV,16,56,87590.549451,305874.306741,12449.0,2954083.0,91.0
22574,Corvette Stingray w/2LT,490.0HP 6.2L 8 Cylinder Engine Gasoline Fuel,1,48,85957.750000,57486.767707,24995.0,491836.0,88.0
44254,M4 Base,425.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,19,48,80074.878049,91706.648891,5500.0,649999.0,82.0
37837,Ghost Base,563.0HP 6.6L 12 Cylinder Engine Gasoline Fuel,79,47,117327.538462,156023.952319,11000.0,749950.0,52.0
44260,M4 Base,425.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,25,45,64617.910256,46962.855099,18749.0,275000.0,78.0
54175,Q5 S line Premium Plus,2.0 Liter TFSI,10,45,41801.407407,21923.460605,5230.0,159998.0,54.0
30913,F-150 XLT,375.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,67,45,36221.916667,11717.503252,13895.0,81500.0,60.0
22585,Corvette Stingray w/2LT,490.0HP 6.2L 8 Cylinder Engine Gasoline Fuel,12,45,77197.216667,64465.194754,14000.0,489000.0,60.0